import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Provider } from "./provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "First next app",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex flex-col h-screen">
                <Provider>
                    <NavBar />
                    {children}
                </Provider>
                <Toaster position="top-center" />
            </body>
        </html>
    );
}
